version: '3.7'

services:
  database_hubbi:
    image: postgres:15
    container_name: database_hubbi
    restart: always
    ports:
      - "5434:5432" 
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
     
  app:
    container_name: hubbi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000" 
    depends_on:
      - database_hubbi
    env_file:
      - .env 
  
volumes:
  postgres:
    name: nest-db




