version: '3.7'

services:
  database_hubbi:
    image: postgres:15
    container_name: database_hubbi
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" 
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
     
  app:
    container_name: hubbi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    depends_on:
      - database_hubbi
    env_file:
      - .env 
  
volumes:
  postgres:
    name: nest-db




